name: Accessibility Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  a11y-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build:prod
    - name: Start static file server
      run: yarn serve docs --no-clipboard --listen 4173 &
    - name: Wait for server
      run: npx wait-on http://localhost:4173 --timeout 60000
    - name: Check for <main> and <h1> in server response
      run: |
        curl -s http://localhost:4173 | grep -q '<main' && echo '<main> found' || (echo 'ERROR: <main> not found' && exit 1)
        curl -s http://localhost:4173 | grep -q '<h1' && echo '<h1> found' || (echo 'ERROR: <h1> not found' && exit 1)
    - name: Run axe accessibility tests
      run: |
        sleep 10
        yarn axe 'http://localhost:4173' --verbose --exit > axe-output.log 2>&1
        cat axe-output.log